theme: jekyll-theme-minimal
title: Mohamed CHELALI
logo: /image/MTC.jpg
description: Doctorant en informatique à l'Université de Paris Descartes.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
